[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "dist"
  port = 8888
  targetPort = 5173
  framework = "vite"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 